include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for RG500Q WebUI
LUCI_DEPENDS:=+rg500q-webserver
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-rg500q-webui
PKG_VERSION:=1.0.1
PKG_RELEASE:=0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

